spring.application.name=todoapp
server.port=8080

# Mongo inside docker-compose
spring.data.mongodb.uri=mongodb://mongo:27017/todoapp

# Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
