server:
  port: 8080


spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/todoapp?authSource=admin
      auto-index-creation: true
  jackson:
    default-property-inclusion: non_null


management:
  endpoints:
    web:
      exposure:
        include: health,info